name: OIDC Demo

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  aws-oidc-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

    #  - name: Print OIDC token claims
    #    run: |
    #      TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
    #      "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com")
    #    echo $TOKEN | cut -d'.' -f2 | base64 -d 2>/dev/null | python3 -m json.tool

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_NAME1 }}
          aws-region: eu-central-1
          role-session-name: GitHubActionsRole 

      - name: Verify identity
        run: aws sts get-caller-identity

      - name: List S3 buckets
        run: aws s3 ls

      #   # ✅ Send Slack Notification on Success
      # - name: Send Slack Notification (Success)
      #     if: success()
      #     run: |
      #       response=$(curl -X POST -H 'Content-type: application/json' --data '{
      #         "text": "🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩\n✅ *OIDC Workflow Completed Successfully!* 🎉\n🚀 *Repository:* `${{ github.repository }}`\n🔗 *Commit:* <${{ github.event.head_commit.url }}|View Commit>\n🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩🟩"
      #       }' ${{ secrets.SLACK_WEBHOOK_URL }} 2>&1)
      #       echo "Slack Response: $response"
  
  
      #   # ❌ Send Slack Notification on Failure
      # - name: Send Slack Notification (Failure)
      #     if: failure()
      #     run: |
      #       response=$(curl -X POST -H 'Content-type: application/json' --data '{
      #         "text": "🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥\n❌ *OIDC Workflow Failed!* 🚨\n💥 *Repository:* `${{ github.repository }}`\n🔗 *Commit:* <${{ github.event.head_commit.url }}|View Commit>\n⚠️ Please check the logs for details.\n🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥🟥"
      #       }' ${{ secrets.SLACK_WEBHOOK_URL }} 2>&1)
      #       echo "Slack Response: $response"
  